// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vwkpyxqltwlzvkmeqjva.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ3a3B5eHFsdHdsenZrbWVxanZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzNjQ0MjcsImV4cCI6MjA2NTk0MDQyN30.bH5i6a_5SYErD9vCRn8ZPlEK7F6wsd9TuI65v_9x6Jk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);